SET SQL_SAFE_UPDATES = 0;

update chuyenmuc set tenchuyenmuc_khongdau='batdongsan' where idchuyenmuc='cm12';
update baiviet set NgayDang ='2019-05-14 00:00:00' where NgayDang='2019-05-05 00:00:00';
update baiviet set chuyenmuc='cm11' where chuyenmuc='cm1';
update baiviet set chuyenmuc='cm21' where chuyenmuc='cm2';
update baiviet set chuyenmuc='cm31' where chuyenmuc='cm3';
update baiviet set chuyenmuc='cm41' where chuyenmuc='cm4';
update baiviet set chuyenmuc='cm51' where chuyenmuc='cm5';
update baiviet set chuyenmuc='cm61' where chuyenmuc='cm6';
update baiviet set chuyenmuc='cm71' where chuyenmuc='cm7';
update baiviet set chuyenmuc='cm81' where chuyenmuc='cm8';
update baiviet set chuyenmuc='cm91' where chuyenmuc='cm9';
update baiviet set tieude_khongdau='Nghi-Duong-Tai-Evason-Ana-Mandara-Nha-Trang' where tieude_khongdau is null;
------------------------------------------

set sql_safe_updates=0;
update nguoidung set AnhDaiDien='avatar.jpg' where AnhDaiDien='2';
update binhluan set NgayBinhLuan='2019-05-19' where NgayBinhLuan is null;
alter table binhluan drop foreign key FK_BL_BL;
update  binhluan  set IDBinhLuan=2 where IDBinhLuan=1 and DocGia=4;

insert into nhan_baiviet values('BV2','tag1');
insert into nhan_baiviet values('BV3','tag1');
insert into nhan_baiviet values('BV4','tag1');
insert into nhan_baiviet values('BV5','tag1');
insert into nhan_baiviet values('BV6','tag1');
insert into nhan_baiviet values('BV7','tag1');
insert into nhan_baiviet values('BV8','tag1');
insert into nhan_baiviet values('BV9','tag1');
insert into nhan_baiviet values('BV10','tag1');
insert into nhan_baiviet values('BV11','tag1');
insert into nhan_baiviet values('BV12','tag1');
insert into nhan_baiviet values('BV13','tag1');
insert into nhan_baiviet values('BV14','tag1');
insert into nhan_baiviet values('BV15','tag1');
insert into nhan_baiviet values('BV16','tag1');
insert into nhan_baiviet values('BV17','tag1');
insert into nhan_baiviet values('BV18','tag1');
insert into nhan_baiviet values('BV19','tag1');
insert into nhan_baiviet values('BV20','tag1');
insert into nhan_baiviet values('BV21','tag1');
insert into nhan_baiviet values('BV22','tag1');
insert into nhan_baiviet values('BV23','tag1');
insert into nhan_baiviet values('BV24','tag1');
insert into nhan_baiviet values('BV25','tag1');
insert into nhan_baiviet values('BV26','tag1');
insert into nhan_baiviet values('BV27','tag1');

insert into nhan_baiviet values('BV2','tag2');
insert into nhan_baiviet values('BV3','tag2');
insert into nhan_baiviet values('BV4','tag2');
insert into nhan_baiviet values('BV5','tag2');
insert into nhan_baiviet values('BV6','tag2');
insert into nhan_baiviet values('BV7','tag2');
insert into nhan_baiviet values('BV8','tag2');
insert into nhan_baiviet values('BV9','tag2');
insert into nhan_baiviet values('BV10','tag2');
insert into nhan_baiviet values('BV11','tag2');
insert into nhan_baiviet values('BV12','tag2');
insert into nhan_baiviet values('BV13','tag2');
insert into nhan_baiviet values('BV14','tag2');
insert into nhan_baiviet values('BV15','tag2');
insert into nhan_baiviet values('BV16','tag2');
insert into nhan_baiviet values('BV17','tag2');
insert into nhan_baiviet values('BV18','tag2');
insert into nhan_baiviet values('BV19','tag2');
insert into nhan_baiviet values('BV20','tag2');
insert into nhan_baiviet values('BV21','tag2');
insert into nhan_baiviet values('BV22','tag2');
insert into nhan_baiviet values('BV23','tag2');
insert into nhan_baiviet values('BV24','tag2');
insert into nhan_baiviet values('BV25','tag2');
insert into nhan_baiviet values('BV26','tag2');
insert into nhan_baiviet values('BV27','tag2');

insert into nhan_baiviet values('BV2','tag3');
insert into nhan_baiviet values('BV3','tag3');
insert into nhan_baiviet values('BV4','tag3');
insert into nhan_baiviet values('BV5','tag3');
insert into nhan_baiviet values('BV6','tag3');
insert into nhan_baiviet values('BV7','tag3');
insert into nhan_baiviet values('BV8','tag3');
insert into nhan_baiviet values('BV9','tag3');
insert into nhan_baiviet values('BV10','tag3');
insert into nhan_baiviet values('BV11','tag3');
insert into nhan_baiviet values('BV12','tag3');
insert into nhan_baiviet values('BV13','tag3');
insert into nhan_baiviet values('BV14','tag3');
insert into nhan_baiviet values('BV15','tag3');
insert into nhan_baiviet values('BV16','tag3');
insert into nhan_baiviet values('BV17','tag3');
insert into nhan_baiviet values('BV18','tag3');
insert into nhan_baiviet values('BV19','tag3');
insert into nhan_baiviet values('BV20','tag3');
insert into nhan_baiviet values('BV21','tag3');
insert into nhan_baiviet values('BV22','tag3');
insert into nhan_baiviet values('BV23','tag3');
insert into nhan_baiviet values('BV24','tag3');
insert into nhan_baiviet values('BV25','tag3');
insert into nhan_baiviet values('BV26','tag3');
insert into nhan_baiviet values('BV27','tag3');

